name: Send Email

on:
  # You can trigger this workflow manually from the GitHub Actions tab
  workflow_dispatch:
  
  # Or use a schedule (this example runs daily at midnight UTC)
  schedule:
    - cron: '30 6 * * *'

jobs:
  send-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          # Add any other dependencies your script needs
      
      - name: Create .env file in 2024 directory
        run: |
          mkdir -p 2024
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" > 2024/.env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> 2024/.env
      
      - name: Run email sender script
        run: python 2024/MailSender.py
        working-directory: .
